In [1]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

/tmp/ipykernel_48146/1646494204.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])


In [2]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [4]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [6]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [7]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [9]:
img_t

tensor([[[-1.5831, -0.4238,  0.3105, -1.3146,  0.4923],
         [ 0.0784,  0.2893, -1.2461,  1.1088, -0.3600],
         [-0.7937,  0.8938,  0.5185, -0.3799, -0.3460],
         [ 0.8064,  0.4486,  1.2623, -0.8450,  0.8281],
         [-0.8567,  1.7735, -2.4414,  1.1648, -1.0989]],

        [[ 2.5220, -1.3231, -0.8238, -0.0152,  0.2151],
         [-0.7359, -1.9474, -0.4078, -0.8671, -0.7557],
         [ 1.0370,  0.7249,  0.3325,  1.2125, -0.6980],
         [ 0.6929, -0.1641,  1.4682, -0.3090,  1.0413],
         [ 1.0770, -0.2593,  1.3552, -0.2441,  0.6417]],

        [[ 0.2387,  0.6139, -0.0387,  0.5136, -0.0392],
         [-0.9932,  0.0913, -0.4339,  0.5757, -1.1833],
         [-0.1101, -0.4281, -0.3595, -1.8122,  2.8633],
         [-1.0104, -0.6954,  0.0087,  0.3208,  0.4111],
         [ 0.3775,  1.4174, -0.1036, -1.0930,  0.6621]]])

In [12]:
batch_named.rename(None)

tensor([[[[ 0.1976, -1.5603, -0.0045, -1.2572,  0.5885],
          [-0.1003,  0.3111,  0.9989,  1.0852,  1.2955],
          [ 1.3837,  0.4713,  0.4735, -0.6076, -0.7892],
          [-0.7479, -0.1799, -0.9949, -0.9648, -0.6326],
          [-0.8645, -1.3328,  1.3083, -0.7171, -0.5308]],

         [[ 0.6961, -0.3234, -0.9508,  1.0607,  0.6286],
          [-0.2541, -0.3004,  0.1852,  0.0747,  0.5703],
          [-1.2282,  2.1270, -0.7372, -0.1612, -0.6412],
          [ 0.3244, -2.0292, -0.7470, -0.3488,  0.3402],
          [-1.5664,  0.8073, -0.8727,  3.4147, -1.4600]],

         [[-1.2205,  0.1338,  0.3889,  0.7897, -0.6711],
          [ 0.7180,  0.6707, -1.0545, -0.5493, -0.4668],
          [-0.2094,  1.0718, -1.0343, -1.0147, -1.0359],
          [-0.5542,  0.2617, -0.4181, -1.0775, -0.2654],
          [ 0.5455,  0.2202,  1.7382, -1.2776,  0.2460]]],


        [[[-0.6350,  1.4596, -1.9408, -0.4513,  0.2957],
          [-0.8001,  2.0459, -0.3588, -0.0855, -1.0849],
          [-1.1966,  0.

In [13]:
batch_t

tensor([[[[ 0.1976, -1.5603, -0.0045, -1.2572,  0.5885],
          [-0.1003,  0.3111,  0.9989,  1.0852,  1.2955],
          [ 1.3837,  0.4713,  0.4735, -0.6076, -0.7892],
          [-0.7479, -0.1799, -0.9949, -0.9648, -0.6326],
          [-0.8645, -1.3328,  1.3083, -0.7171, -0.5308]],

         [[ 0.6961, -0.3234, -0.9508,  1.0607,  0.6286],
          [-0.2541, -0.3004,  0.1852,  0.0747,  0.5703],
          [-1.2282,  2.1270, -0.7372, -0.1612, -0.6412],
          [ 0.3244, -2.0292, -0.7470, -0.3488,  0.3402],
          [-1.5664,  0.8073, -0.8727,  3.4147, -1.4600]],

         [[-1.2205,  0.1338,  0.3889,  0.7897, -0.6711],
          [ 0.7180,  0.6707, -1.0545, -0.5493, -0.4668],
          [-0.2094,  1.0718, -1.0343, -1.0147, -1.0359],
          [-0.5542,  0.2617, -0.4181, -1.0775, -0.2654],
          [ 0.5455,  0.2202,  1.7382, -1.2776,  0.2460]]],


        [[[-0.6350,  1.4596, -1.9408, -0.4513,  0.2957],
          [-0.8001,  2.0459, -0.3588, -0.0855, -1.0849],
          [-1.1966,  0.

In [14]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [15]:
weights_aligned = weights_named.align_as(img_named)

In [18]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [19]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [11]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [12]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))