In [1]:
import torch

In [2]:
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[2]

tensor(1.)

In [4]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [25]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [8]:
weights.unsqueeze(1)

tensor([[0.2126],
        [0.7152],
        [0.0722]])

In [10]:
weights.unsqueeze?

Docstring:
unsqueeze(dim) -> Tensor

See :func:`torch.unsqueeze`
Type:      builtin_function_or_method


In [12]:
weights.unsqueeze(0)

tensor([[0.2126, 0.7152, 0.0722]])

In [20]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)

In [23]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [24]:
img_t.refine_names(..., 'channels', 'rows', 'columns')

/home/inigo/dl/2020-dlwpt/.venv/lib/python3.10/site-packages/torch/_tensor.py:1105: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  return super(Tensor, self).refine_names(names)


tensor([[[ 0.8036, -0.9316, -0.6373, -1.4347,  0.9375],
         [ 0.8515, -0.1080, -1.0595,  1.4778, -0.1260],
         [ 0.1127,  0.2497,  2.3881,  0.2079,  0.4195],
         [ 0.2861, -0.8131, -1.3408,  0.8461,  0.5869],
         [-0.3661,  0.7606,  1.5774, -1.8758,  1.0469]],

        [[ 0.1742, -1.6002, -0.5357,  0.8952,  0.6416],
         [ 0.3047, -0.3877, -0.0499, -0.6046,  0.9074],
         [ 0.0484,  0.6979,  1.4784,  1.0756,  0.7823],
         [-0.5834,  1.9722,  0.6251,  2.8408, -0.9974],
         [-0.7189, -0.0068, -0.4164,  0.1541, -0.4887]],

        [[ 1.6945, -0.0338,  1.2907,  0.0141,  0.3737],
         [ 0.4069, -0.2132,  0.0646, -0.2493, -0.8528],
         [ 0.2917, -0.7763,  0.7214, -0.2477, -0.3638],
         [-1.6562,  1.6603, -0.8035,  0.3702, -0.9543],
         [-0.6786, -0.6274,  0.0695,  1.6595,  2.1415]]],
       names=('channels', 'rows', 'columns'))

In [22]:
img_t

tensor([[[ 0.8036, -0.9316, -0.6373, -1.4347,  0.9375],
         [ 0.8515, -0.1080, -1.0595,  1.4778, -0.1260],
         [ 0.1127,  0.2497,  2.3881,  0.2079,  0.4195],
         [ 0.2861, -0.8131, -1.3408,  0.8461,  0.5869],
         [-0.3661,  0.7606,  1.5774, -1.8758,  1.0469]],

        [[ 0.1742, -1.6002, -0.5357,  0.8952,  0.6416],
         [ 0.3047, -0.3877, -0.0499, -0.6046,  0.9074],
         [ 0.0484,  0.6979,  1.4784,  1.0756,  0.7823],
         [-0.5834,  1.9722,  0.6251,  2.8408, -0.9974],
         [-0.7189, -0.0068, -0.4164,  0.1541, -0.4887]],

        [[ 1.6945, -0.0338,  1.2907,  0.0141,  0.3737],
         [ 0.4069, -0.2132,  0.0646, -0.2493, -0.8528],
         [ 0.2917, -0.7763,  0.7214, -0.2477, -0.3638],
         [-1.6562,  1.6603, -0.8035,  0.3702, -0.9543],
         [-0.6786, -0.6274,  0.0695,  1.6595,  2.1415]]])

In [ ]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape